//
//  History.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.12
//

import Foundation
import UIKit
import AWSDynamoDB

class History: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _rideID: String?
    var _averageSpeed: NSNumber?
    var _caloriesBurned: NSNumber?
    var _distance: NSNumber?
    var _time: String?
    
    class func dynamoDBTableName() -> String {

        return "nimbleride-mobilehub-95138682-History"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_rideID"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_rideID" : "RideID",
               "_averageSpeed" : "Average Speed",
               "_caloriesBurned" : "Calories Burned",
               "_distance" : "Distance",
               "_time" : "Time",
        ]
    }
}
