# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NimbleRide' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NimbleRide
  pod 'SpeechKit'

  target 'NimbleRideTests' do
    inherit! :search_paths
    
    # Pods for testing
    pod 'SpeechKit'
  end

  target 'NimbleRideUITests' do
    inherit! :search_paths

    # Pods for testing
    pod 'SpeechKit'
  end

end
